/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateOrderItem { 'productId' : bigint, 'quantity' : bigint }
export interface Customer {
  'id' : bigint,
  'customerName' : string,
  'gstNumber' : string,
  'createdAt' : bigint,
  'email' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
  'phoneVerified' : boolean,
}
export interface DashboardStats {
  'totalOrders' : bigint,
  'lowStockProducts' : bigint,
  'recentOrders' : Array<Order>,
  'totalRevenue' : number,
  'totalCustomers' : bigint,
}
export interface Order {
  'customerName' : string,
  'status' : string,
  'orderDate' : bigint,
  'orderId' : bigint,
  'totalAmount' : number,
  'companyName' : string,
  'customerId' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'id' : bigint,
  'productId' : bigint,
  'productName' : string,
  'orderId' : bigint,
  'quantity' : bigint,
  'price' : number,
}
export interface Product {
  'stockQuantity' : bigint,
  'name' : string,
  'productId' : bigint,
  'category' : string,
  'price' : number,
}
export interface _SERVICE {
  'addCustomer' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : boolean, 'customer' : [] | [Customer], 'message' : string }
  >,
  'addProduct' : ActorMethod<
    [string, string, number, bigint],
    { 'ok' : boolean, 'message' : string, 'product' : [] | [Product] }
  >,
  'createOrder' : ActorMethod<
    [bigint, Array<CreateOrderItem>],
    { 'ok' : boolean, 'orderId' : [] | [bigint], 'message' : string }
  >,
  'deleteCustomer' : ActorMethod<
    [bigint],
    { 'ok' : boolean, 'message' : string }
  >,
  'deleteProduct' : ActorMethod<
    [bigint],
    { 'ok' : boolean, 'message' : string }
  >,
  'getCustomers' : ActorMethod<[string], Array<Customer>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getInvoice' : ActorMethod<[bigint], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'searchCustomers' : ActorMethod<[string], Array<Customer>>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'updateCustomer' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    { 'ok' : boolean, 'message' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [bigint, string],
    { 'ok' : boolean, 'message' : string }
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, bigint],
    { 'ok' : boolean, 'message' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];