/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'gstNumber' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'phoneVerified' : IDL.Bool,
});
export const Product = IDL.Record({
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'productId' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const CreateOrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const OrderItem = IDL.Record({
  'id' : IDL.Nat,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'orderId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'orderDate' : IDL.Int,
  'orderId' : IDL.Nat,
  'totalAmount' : IDL.Float64,
  'companyName' : IDL.Text,
  'customerId' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const DashboardStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'lowStockProducts' : IDL.Nat,
  'recentOrders' : IDL.Vec(Order),
  'totalRevenue' : IDL.Float64,
  'totalCustomers' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [
        IDL.Record({
          'ok' : IDL.Bool,
          'customer' : IDL.Opt(Customer),
          'message' : IDL.Text,
        }),
      ],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [
        IDL.Record({
          'ok' : IDL.Bool,
          'message' : IDL.Text,
          'product' : IDL.Opt(Product),
        }),
      ],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Nat, IDL.Vec(CreateOrderItem)],
      [
        IDL.Record({
          'ok' : IDL.Bool,
          'orderId' : IDL.Opt(IDL.Nat),
          'message' : IDL.Text,
        }),
      ],
      [],
    ),
  'deleteCustomer' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'deleteProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'getCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'searchCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
  'seedDemoData' : IDL.Func([], [], []),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'gstNumber' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'phoneVerified' : IDL.Bool,
  });
  const Product = IDL.Record({
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'productId' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const CreateOrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const OrderItem = IDL.Record({
    'id' : IDL.Nat,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'orderId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'orderDate' : IDL.Int,
    'orderId' : IDL.Nat,
    'totalAmount' : IDL.Float64,
    'companyName' : IDL.Text,
    'customerId' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const DashboardStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'lowStockProducts' : IDL.Nat,
    'recentOrders' : IDL.Vec(Order),
    'totalRevenue' : IDL.Float64,
    'totalCustomers' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [
          IDL.Record({
            'ok' : IDL.Bool,
            'customer' : IDL.Opt(Customer),
            'message' : IDL.Text,
          }),
        ],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [
          IDL.Record({
            'ok' : IDL.Bool,
            'message' : IDL.Text,
            'product' : IDL.Opt(Product),
          }),
        ],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Nat, IDL.Vec(CreateOrderItem)],
        [
          IDL.Record({
            'ok' : IDL.Bool,
            'orderId' : IDL.Opt(IDL.Nat),
            'message' : IDL.Text,
          }),
        ],
        [],
      ),
    'deleteCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'deleteProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'getCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'searchCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
    'seedDemoData' : IDL.Func([], [], []),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };